# Name used in ./cd-preview-deploy.yaml
name: CD - Preview Build

on:
    pull_request:
      types: [opened, synchronize]

jobs:
  build-app-preview:
    runs-on: ubuntu-latest
    name: Build app and upload build artifact
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Build the app
        run: pnpm -F @pas-fute-fute/app build:cloudflare

      # Uploads the build directory as a workflow artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: preview-app-build
          if-no-files-found: error
          path: packages/app/dist